### ISSUE TITLE
Renderer Update takes minutes to complete

### ISSUE THREAD

**Issue by AmazingTurtle** [ultralight-ux/Ultralight#190] opened 2019-10-19 18:16 UTC
```
#include "stdafx.h"
#include <Ultralight/Ultralight.h>
#include <AppCore/AppCore.h>
#include "UltralightUI.hpp"

#pragma comment(lib, "Ultralight.lib")
#pragma comment(lib, "UltralightCore.lib")
#pragma comment(lib, "WebCore.lib")

using namespace ultralight;

UltralightUI::UltralightUI() {
	this->width = 1024;
	this->height = 768;
	this->renderer_ = Renderer::Create();
	this->view_ = renderer_->CreateView(this->width, this->height, false);
	this->view_->LoadURL("http://localhost:3000/");
}
void UltralightUI::Update() {
	MessageBoxA(NULL, "Update started", "ULUI", 0);
	this->renderer_->Update();
	MessageBoxA(NULL, "Update ended", "ULUI", 0);
}

...
```

Update is called from the main thread loop. It takes minutes to complete (each time it takes a bit longer). Why is that?
On localhost:3000 I'm serving a nextjs dev page.

**Comment by adamjs** [comment] 2019-10-19 18:18
Hmm, can you give more info regarding your "nextjs dev page" so I can reproduce on my side and debug?

**Comment by adamjs** [comment] 2019-10-19 18:36
From slack:
> Turtle 1:32 PM
https://github.com/iaincollins/nextjs-starter
> Platform: Windows, also seems to have an access violation in UltralightCore.

I'll trace and debug.

**Comment by adamjs** [comment] 2020-07-14 16:40
Retested this today and seems to be fixed in latest trunk.

**Closed by adamjs** 2020-07-14 16:40 UTC
Labels: bug
