### ISSUE TITLE
Support `WebAudio` APIs

### ISSUE THREAD

**Issue by alecgorge** [ultralight-ux/Ultralight#11] opened 2018-08-10 17:30 UTC
**Is your feature request related to a problem? Please describe.**

I would like to use Ultralight for a webapp that plays music. We make use of the HTML5 audio tag and the `WebAudio` classes themselves. I'd say HTML5 audio tag is higher priority but it'd be nice to have both.

**Describe the solution you'd like**

1. https://html.spec.whatwg.org/multipage/media.html#the-audio-element
2. The WebAudio API as a whole is huge so I don't view this as a priority: https://www.w3.org/TR/webaudio/

**Describe alternatives you've considered**

None? There's no way to play audio.

**Additional context**

**Comment by raff** [comment] 2019-05-07 01:28
Is this a matter of enabling WEB_AUDIO in WebCore and then tweak something in here ? Or there is more ?

**Comment by adamjs** [comment] 2020-07-04 18:15
Duplicate of #217 (in progress).

**Closed by adamjs** 2020-07-04 18:15 UTC
Labels: enhancement
