### ISSUE TITLE
support video tag html

### ISSUE THREAD

**Issue by rafadsm** [ultralight-ux/Ultralight#72] opened 2018-12-27 15:04 UTC
**Is your feature request related to a problem? Please describe.**
It does not support the html video tag, I have components that use local videos as background

**Describe the solution you'd like**
HTML VIDEO

<video class="video-btn" loop>
     <source src="dist/myvideo.webm" type="video/webm">
</video>

**Comment by adamjs** [comment] 2020-07-04 18:16
Duplicate of #217 (in progress).

**Closed by adamjs** 2020-07-04 18:16 UTC
